"use strict";this.default_uiframehook=this.default_uiframehook||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.l=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.m=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.q=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ff=function(a,c,f){for(var h=Array(arguments.length-2),n=2;n<arguments.length;n++)h[n-2]=arguments[n];return b.prototype[c].apply(a,h)}};
_.fa=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.r.apply(null,arguments)};_.ga=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ha=function(a){return"function"==ea(a)};_.ia=function(a){return"number"==typeof a};
_.t=function(a){return"string"==typeof a};_.ja=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.v=function(a){return"array"==ea(a)};_.ka=function(a){a.Ja=function(){return a.Pc?a.Pc:a.Pc=new a}};_.la=function(){};_.ma=function(a){a=a.split(".");for(var b=_.k,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};_.na=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.na);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.q(_.na,Error);_.na.prototype.name="CustomError";
var qa,ta;_.oa=function(a){return/^[\s\xa0]*$/.test(a)};qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.ra=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.sa=function(a){return null==a?"":String(a)};
_.va=function(a,b){for(var c=0,d=qa(String(a)).split("."),e=qa(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var n=d[h]||"",p=e[h]||"",u=RegExp("(\\d*)(\\D*)","g"),X=RegExp("(\\d*)(\\D*)","g");do{var ua=u.exec(n)||["","",""],pa=X.exec(p)||["","",""];if(0==ua[0].length&&0==pa[0].length)break;c=ta(0==ua[1].length?0:(0,window.parseInt)(ua[1],10),0==pa[1].length?0:(0,window.parseInt)(pa[1],10))||ta(0==ua[2].length,0==pa[2].length)||ta(ua[2],pa[2])}while(0==c)}return c}; ta=function(a,b){return a<b?-1:a>b?1:0};
_.wa=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.xa=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.w=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ya=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,n=0;n<d;n++)if(n in h){var p=h[n];b.call(c,p,n,a)&&(e[f++]=p)}return e};_.za=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.Aa=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,_.r)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.w)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};_.Ba=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Da=function(a,b){var c=_.Ca(a,b,void 0);return 0>c?null:_.t(a)?a.charAt(c):a[c]};
_.Ca=function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.Ea=function(a,b){return 0<=(0,_.wa)(a,b)};_.Ga=function(a,b){var c=(0,_.wa)(a,b),d;(d=0<=c)&&_.Fa(a,c);return d};_.Fa=function(a,b){Array.prototype.splice.call(a,b,1)};_.Ha=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.Ia=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Ja,La,Ka,Oa,Pa,Na;Ja=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.Ma=function(a){var b=[];Ka(new La,a,b);return b.join("")};La=function(){};
Ka=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.v(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Ka(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Na(d,c),c.push(":"),Ka(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Na(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};Oa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Pa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;Na=function(a,b){b.push('"',a.replace(Pa,function(a){var b=Oa[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Oa[a]=b);return b}),'"')};
var Ra,Sa,Ta;_.Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};Ra=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Sa=function(a){return null!==a&&"withCredentials"in a};Ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Ua=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ta.length;f++)c=Ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.x=function(){this.R=this.R;this.F=this.F};_.x.prototype.R=!1;_.x.prototype.cc=function(){return this.R};_.x.prototype.T=function(){this.R||(this.R=!0,this.K())};_.x.prototype.K=function(){if(this.F)for(;this.F.length;)this.F.shift()()};a:{var Wa=_.k.navigator;if(Wa){var Xa=Wa.userAgent;if(Xa){_.Va=Xa;break a}}_.Va=""}_.y=function(a){return-1!=_.Va.indexOf(a)};var Ya=function(){return _.y("Opera")||_.y("OPR")},Za=function(){return(_.y("Chrome")||_.y("CriOS"))&&!Ya()&&!_.y("Edge")};var $a;$a=function(){return _.y("iPhone")&&!_.y("iPod")&&!_.y("iPad")};_.ab=function(){return _.y("Windows")};var bb,db,gb,kb,lb,mb,nb,pb;bb=Ya();_.cb=_.y("Trident")||_.y("MSIE");db=_.y("Edge");_.eb=_.y("Gecko")&&!(-1!=_.Va.toLowerCase().indexOf("webkit")&&!_.y("Edge"))&&!(_.y("Trident")||_.y("MSIE"))&&!_.y("Edge");_.fb=-1!=_.Va.toLowerCase().indexOf("webkit")&&!_.y("Edge");gb=_.k.navigator||null;_.hb=gb&&gb.platform||"";_.ib=_.y("Macintosh");_.jb=_.ab();
kb=function(){var a=_.Va;if(_.eb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(db)return/Edge\/([\d\.]+)/.exec(a);if(_.cb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.fb)return/WebKit\/(\S+)/.exec(a)};lb=function(){var a=_.k.document;return a?a.documentMode:void 0};mb=function(){if(bb&&_.k.opera){var a;var b=_.k.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=kb())&&(a=b?b[1]:"");return _.cb&&(b=lb(),b>(0,window.parseFloat)(a))?String(b):a}();nb={}; _.ob=function(a){return nb[a]||(nb[a]=0<=_.va(mb,a))};pb=_.k.document;_.qb=pb&&_.cb?lb()||("CSS1Compat"==pb.compatMode?(0,window.parseInt)(mb,10):5):void 0;
var rb=function(){this.b="";this.a=null},sb=function(a){var b=new rb;b.b=a;b.a=0};sb("<!DOCTYPE html>");sb("");var tb="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""},ub=function(){};ub.prototype.next=function(){throw tb;};ub.prototype.Aa=function(){return this};
var vb=function(a){if(a instanceof ub)return a;if("function"==typeof a.Aa)return a.Aa(!1);if(_.ja(a)){var b=0,c=new ub;c.next=function(){for(;;){if(b>=a.length)throw tb;if(b in a)return a[b++];b++}};return c}throw Error("h");},wb=function(a,b){if(_.ja(a))try{(0,_.w)(a,b,void 0)}catch(c){if(c!==tb)throw c;}else{a=vb(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==tb)throw c;}}},xb=function(a){if(_.ja(a))return _.Ia(a);a=vb(a);var b=[];wb(a,function(a){b.push(a)});return b};
_.z=function(a,b){this.b={};this.a=[];this.g=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("e");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.z?(c=a.ba(),d=a.U()):(c=Ra(a),d=_.Qa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.z.prototype.ta=function(){return this.c};_.z.prototype.U=function(){yb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.z.prototype.ba=function(){yb(this);return this.a.concat()};
_.Ab=function(a,b){return zb(a.b,b)};_.z.prototype.la=function(){return 0==this.c};_.z.prototype.clear=function(){this.b={};this.g=this.c=this.a.length=0};_.z.prototype.remove=function(a){return zb(this.b,a)?(delete this.b[a],this.c--,this.g++,this.a.length>2*this.c&&yb(this),!0):!1};
var yb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];zb(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],zb(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.g=_.z.prototype;_.g.get=function(a,b){return zb(this.b,a)?this.b[a]:b};_.g.set=function(a,b){zb(this.b,a)||(this.c++,this.a.push(a),this.g++);this.b[a]=b};_.g.forEach=function(a,b){for(var c=this.ba(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.g.clone=function(){return new _.z(this)};_.g.Aa=function(a){yb(this);var b=0,c=this.g,d=this,e=new ub;e.next=function(){if(c!=d.g)throw Error("i");if(b>=d.a.length)throw tb;var e=d.a[b++];return a?e:d.b[e]};return e};var zb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Bb=function(a){if(a.U&&"function"==typeof a.U)return a.U();if(_.t(a))return a.split("");if(_.ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return _.Qa(a)};
_.Cb=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(_.ja(a)||_.t(a))(0,_.w)(a,b,c);else{var d;if(a.ba&&"function"==typeof a.ba)d=a.ba();else if(a.U&&"function"==typeof a.U)d=void 0;else if(_.ja(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Ra(a);for(var e=_.Bb(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};
var Db=function(a,b,c){this.g=c;this.c=a;this.h=b;this.b=0;this.a=null};Db.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Eb=function(a,b){a.h(b);a.b<a.g&&(a.b++,b.next=a.a,a.a=b)};var Ib;_.Fb=[];_.Gb=[];_.Hb=!1;Ib=function(a){_.Fb[_.Fb.length]=a;if(_.Hb)for(var b=0;b<_.Gb.length;b++)a((0,_.r)(_.Gb[b].b,_.Gb[b]))};var Kb=function(a){_.k.setTimeout(function(){throw a;},0)},Lb,Mb=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.y("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+
"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.y("Trident")&&!_.y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.zc;c.zc=null;a()}};return function(a){d.next={zc:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in
window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}},Nb=function(a){return a};Ib(function(a){Nb=a});
var Ob=function(){this.b=this.a=null},Qb=new Db(function(){return new Pb},function(a){a.reset()},100);Ob.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Pb=function(){this.next=this.b=this.a=null};Pb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Pb.prototype.reset=function(){this.next=this.b=this.a=null};
var Vb=function(a,b){Rb||Sb();Tb||(Rb(),Tb=!0);var c=Ub,d=Qb.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},Rb,Sb=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve(void 0);Rb=function(){a.then(Wb)}}else Rb=function(){var a=Wb,a=Nb(a);!_.ha(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&!_.y("Edge")&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Lb||(Lb=Mb()),Lb(a)):_.k.setImmediate(a)}},Tb=!1,Ub=new Ob,Wb=function(){for(var a=null;a=Ub.remove();){try{a.a.call(a.b)}catch(b){Kb(b)}Eb(Qb, a)}Tb=!1};
_.Xb=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};_.Yb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ac,bc,fc,dc,kc,ic,gc,hc,mc,lc,nc;_.$b=function(a,b){this.a=0;this.j=void 0;this.g=this.b=this.c=null;this.h=this.F=!1;if(a!=_.la)try{var c=this;a.call(b,function(a){_.Zb(c,2,a)},function(a){_.Zb(c,3,a)})}catch(d){_.Zb(this,3,d)}};ac=function(){this.next=this.context=this.b=this.g=this.a=null;this.c=!1};ac.prototype.reset=function(){this.context=this.b=this.g=this.a=null;this.c=!1};bc=new Db(function(){return new ac},function(a){a.reset()},100);
_.cc=function(a,b,c){var d=bc.get();d.g=a;d.b=b;d.context=c;return d};_.$b.prototype.then=function(a,b,c){return dc(this,_.ha(a)?a:null,_.ha(b)?b:null,c)};_.Xb(_.$b);_.$b.prototype.l=function(a){0==this.a&&Vb(function(){var b=new _.ec(a);fc(this,b)},this)};
fc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.c||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?fc(c,b):(f?(d=f,d.next==c.g&&(c.g=d),d.next=d.next.next):gc(c),hc(c,e,3,b)))}a.c=null}else _.Zb(a,3,b)};_.jc=function(a,b){a.b||2!=a.a&&3!=a.a||ic(a);a.g?a.g.next=b:a.b=b;a.g=b};
dc=function(a,b,c,d){var e=_.cc(null,null,null);e.a=new _.$b(function(a,h){e.g=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){h(u)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof _.ec?h(b):a(e)}catch(u){h(u)}}:h});e.a.c=a;_.jc(a,e);return e.a};_.$b.prototype.D=function(a){this.a=0;_.Zb(this,2,a)};_.$b.prototype.v=function(a){this.a=0;_.Zb(this,3,a)};
_.Zb=function(a,b,c){if(0==a.a){a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.D,h=a.v;if(e instanceof _.$b)_.jc(e,_.cc(f||_.la,h||null,a)),d=!0;else if(_.Yb(e))e.then(f,h,a),d=!0;else{if(_.ga(e))try{var n=e.then;if(_.ha(n)){kc(e,n,f,h,a);d=!0;break a}}catch(p){h.call(a,p);d=!0;break a}d=!1}}d||(a.j=c,a.a=b,a.c=null,ic(a),3!=b||c instanceof _.ec||lc(a,c))}};
kc=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},n=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,n)}catch(p){n(p)}};ic=function(a){a.F||(a.F=!0,Vb(a.w,a))};gc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.g=null);return b};_.$b.prototype.w=function(){for(var a=null;a=gc(this);)hc(this,a,this.a,this.j);this.F=!1};
hc=function(a,b,c,d){if(3==c&&b.b&&!b.c)for(;a&&a.h;a=a.c)a.h=!1;if(b.a)b.a.c=null,mc(b,c,d);else try{b.c?b.g.call(b.context):mc(b,c,d)}catch(e){nc.call(null,e)}Eb(bc,b)};mc=function(a,b,c){2==b?a.g.call(a.context,c):a.b&&a.b.call(a.context,c)};lc=function(a,b){a.h=!0;Vb(function(){a.h&&nc.call(null,b)})};nc=Kb;_.ec=function(a){_.na.call(this,a)};_.q(_.ec,_.na);_.ec.prototype.name="cancel";
var oc=!_.cb||9<=_.qb,pc=_.cb&&!_.ob("9");!_.fb||_.ob("528");_.eb&&_.ob("1.9b")||_.cb&&_.ob("8")||bb&&_.ob("9.5")||_.fb&&_.ob("528");_.eb&&!_.ob("8")||_.cb&&_.ob("9");_.A=function(a,b){this.type="undefined"!=typeof _.qc&&a instanceof _.qc?String(a):a;this.c=this.target=b;this.g=!1;this.ad=!0};_.A.prototype.l=function(){this.g=!0};_.A.prototype.b=function(){this.ad=!1};var rc=function(a){rc[" "](a);return a};rc[" "]=_.la;_.sc=function(a,b){try{return rc(a[b]),!0}catch(c){}return!1};var tc=function(a,b){_.A.call(this,a?a.type:"");this.c=this.target=null;this.keyCode=this.clientY=this.clientX=0;this.h=this.w=this.F=this.j=!1;this.a=this.state=null;if(a){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.c=b;var d=a.relatedTarget;d&&_.eb&&_.sc(d,"nodeName");null===c?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=
void 0!==c.clientY?c.clientY:c.pageY);this.keyCode=a.keyCode||0;this.j=a.ctrlKey;this.F=a.altKey;this.w=a.shiftKey;this.h=a.metaKey;this.state=a.state;this.a=a;a.defaultPrevented&&this.b()}};_.q(tc,_.A);tc.prototype.l=function(){tc.H.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0}; tc.prototype.b=function(){tc.H.b.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,pc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var uc,wc;uc="closure_listenable_"+(1E6*Math.random()|0);_.vc=function(a){return!(!a||!a[uc])};wc=0;var xc=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.$a=!!d;this.Ab=e;this.key=++wc;this.removed=this.sb=!1},yc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ab=null};var zc=function(a){this.src=a;this.a={};this.b=0},Bc=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var n=Ac(b,c,e,f);-1<n?(a=b[n],d||(a.sb=!1)):(a=new xc(c,a.src,h,!!e,f),a.sb=d,b.push(a));return a},Ac;zc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Ac(e,b,c,d);return-1<b?(yc(e[b]),_.Fa(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Cc=function(a,b){var c=b.type;c in a.a&&_.Ga(a.a[c],b)&&(yc(b),0==a.a[c].length&&(delete a.a[c],a.b--))};zc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,yc(d[e]);delete this.a[c];this.b--}return b};_.Dc=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Ac(a,c,d,e));return-1<b?a[b]:null};Ac=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.$a==!!c&&f.Ab==d)return e}return-1};
var Ec,Fc,Gc,Lc,Mc,Rc,Qc,Nc,Sc;Ec="closure_lm_"+(1E6*Math.random()|0);Fc={};Gc=0;_.Hc=function(a,b,c,d,e){if(_.v(b)){for(var f=0;f<b.length;f++)_.Hc(a,b[f],c,d,e);return null}c=_.Ic(c);return _.vc(a)?a.listen(b,c,d,e):_.Jc(a,b,c,!1,d,e)};
_.Jc=function(a,b,c,d,e,f){if(!b)throw Error("j");var h=!!e,n=_.Kc(a);n||(a[Ec]=n=new zc(a));c=Bc(n,b,c,d,e,f);if(c.proxy)return c;d=Lc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(Mc(b.toString()),d);else throw Error("k");Gc++;return c};Lc=function(){var a=Nc,b=oc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Oc=function(a,b,c,d,e){if(_.v(b))for(var f=0;f<b.length;f++)_.Oc(a,b[f],c,d,e);else c=_.Ic(c),_.vc(a)?a.Hb(b,c,d,e):a&&(a=_.Kc(a))&&(b=_.Dc(a,b,c,!!d,e))&&_.Pc(b)};_.Pc=function(a){if(!_.ia(a)&&a&&!a.removed){var b=a.src;if(_.vc(b))Cc(b.sa,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.$a):b.detachEvent&&b.detachEvent(Mc(c),d);Gc--;(c=_.Kc(b))?(Cc(c,a),0==c.b&&(c.src=null,b[Ec]=null)):yc(a)}}};Mc=function(a){return a in Fc?Fc[a]:Fc[a]="on"+a};
Rc=function(a,b,c,d){var e=!0;if(a=_.Kc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.$a==c&&!f.removed&&(f=Qc(f,d),e=e&&!1!==f)}return e};Qc=function(a,b){var c=a.listener,d=a.Ab||a.src;a.sb&&_.Pc(a);return c.call(d,b)};
Nc=function(a,b){if(a.removed)return!0;if(!oc){var c=b||_.ma("window.event"),d=new tc(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.c;f;f=f.parentNode)c.push(f);for(var f=a.type,h=c.length-1;!d.g&&0<=h;h--){d.c=c[h];var n=Rc(c[h],f,!0,d),e=e&&n}for(h=0;!d.g&&h<c.length;h++)d.c=c[h],n=Rc(c[h],f,!1,d),e=e&&n}return e}return Qc(a,new tc(b,this))}; _.Kc=function(a){a=a[Ec];return a instanceof zc?a:null};Sc="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ic=function(a){if(_.ha(a))return a;a[Sc]||(a[Sc]=function(b){return a.handleEvent(b)});return a[Sc]};Ib(function(a){Nc=a(Nc)});
_.B=function(){_.x.call(this);this.sa=new zc(this);this.ma=this;this.w=null};_.q(_.B,_.x);_.B.prototype[uc]=!0;_.B.prototype.D=function(a){this.w=a};_.B.prototype.addEventListener=function(a,b,c,d){_.Hc(this,a,b,c,d)};_.B.prototype.removeEventListener=function(a,b,c,d){_.Oc(this,a,b,c,d)};
_.C=function(a,b){var c,d=a.w;if(d)for(c=[];d;d=d.w)c.push(d);var d=a.ma,e=b,f=e.type||e;if(_.t(e))e=new _.A(e,d);else if(e instanceof _.A)e.target=e.target||d;else{var h=e,e=new _.A(f,d);_.Ua(e,h)}var h=!0,n;if(c)for(var p=c.length-1;!e.g&&0<=p;p--)n=e.c=c[p],h=n.X(f,!0,e)&&h;e.g||(n=e.c=d,h=n.X(f,!0,e)&&h,e.g||(h=n.X(f,!1,e)&&h));if(c)for(p=0;!e.g&&p<c.length;p++)n=e.c=c[p],h=n.X(f,!1,e)&&h;return h};_.g=_.B.prototype;
_.g.K=function(){_.B.H.K.call(this);this.sa&&this.sa.removeAll(void 0);this.w=null};_.g.listen=function(a,b,c,d){return Bc(this.sa,String(a),b,!1,c,d)};_.g.wb=function(a,b,c,d){return Bc(this.sa,String(a),b,!0,c,d)};_.g.Hb=function(a,b,c,d){return this.sa.remove(String(a),b,c,d)}; _.g.X=function(a,b,c){a=this.sa.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.$a==b){var h=f.listener,n=f.Ab||f.src;f.sb&&Cc(this.sa,f);d=!1!==h.call(n,c)&&d}}return d&&0!=c.ad};
var Tc=function(){};Tc.prototype.a=null;var Vc=function(a){var b;(b=a.a)||(b={},Uc(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Wc,Xc=function(){};_.q(Xc,Tc);var Yc=function(a){return(a=Uc(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Uc=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("l");}return a.b};Wc=new Xc;
_.Zc=function(a,b,c){if(_.ha(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("m");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.$c=function(a){_.k.clearTimeout(a)};var bd;_.ad=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;bd=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,h=null;0<=e?(f=c[d].substring(0,e),h=c[d].substring(e+1)):f=c[d];b(f,h?(0,window.decodeURIComponent)(h.replace(/\+/g," ")):"")}};
var dd,hd,md,od,nd,jd,pd;_.cd=function(a){_.B.call(this);this.$=new _.z;this.B=a||null;this.b=!1;this.A=this.a=null;this.M="";this.g=0;this.h="";this.c=this.L=this.l=this.J=!1;this.j=0;this.v=null;this.ca="";this.V=this.ia=!1};_.q(_.cd,_.B);dd=/^https?$/i;_.ed=["POST","PUT"];_.fd=[];_.gd=function(a,b,c,d,e,f,h){var n=new _.cd;_.fd.push(n);b&&n.listen("complete",b);n.wb("ready",n.ja);f&&(n.j=Math.max(0,f));h&&(n.ia=h);n.send(a,c,d,e)};_.cd.prototype.ja=function(){this.T();_.Ga(_.fd,this)};
_.cd.prototype.send=function(a,b,c,d){if(this.a)throw Error("n`"+this.M+"`"+a);b=b?b.toUpperCase():"GET";this.M=a;this.h="";this.g=0;this.J=!1;this.b=!0;this.a=this.B?Yc(this.B):Yc(Wc);this.A=this.B?Vc(this.B):Vc(Wc);this.a.onreadystatechange=(0,_.r)(this.ea,this);try{this.L=!0,this.a.open(b,String(a),!0),this.L=!1}catch(f){hd(this,f);return}a=c||"";var e=this.$.clone();d&&_.Cb(d,function(a,b){e.set(b,a)});d=_.Da(e.ba(),id);c=_.k.FormData&&a instanceof _.k.FormData;!_.Ea(_.ed,b)||d||c||e.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.ca&&(this.a.responseType=this.ca);Sa(this.a)&&(this.a.withCredentials=this.ia);try{jd(this),0<this.j&&((this.V=kd(this.a))?(this.a.timeout=this.j,this.a.ontimeout=(0,_.r)(this.fa,this)):this.v=_.Zc(this.fa,this.j,this)),this.l=!0,this.a.send(a),this.l=!1}catch(f){hd(this,f)}};
var kd=function(a){return _.cb&&_.ob(9)&&_.ia(a.timeout)&&_.m(a.ontimeout)},id=function(a){return"content-type"==a.toLowerCase()};_.cd.prototype.fa=function(){"undefined"!=typeof _.aa&&this.a&&(this.h="Timed out after "+this.j+"ms, aborting",this.g=8,_.C(this,"timeout"),_.ld(this,8))};hd=function(a,b){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.h=b;a.g=5;md(a);nd(a)};md=function(a){a.J||(a.J=!0,_.C(a,"complete"),_.C(a,"error"))};
_.ld=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.g=b||7,_.C(a,"complete"),_.C(a,"abort"),nd(a))};_.cd.prototype.K=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),nd(this,!0));_.cd.H.K.call(this)};_.cd.prototype.ea=function(){this.R||(this.L||this.l||this.c?od(this):this.O())};_.cd.prototype.O=function(){od(this)};
od=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.A[1]||4!=pd(a)||2!=_.qd(a)))if(a.l&&4==pd(a))_.Zc(a.ea,0,a);else if(_.C(a,"readystatechange"),4==pd(a)){a.b=!1;try{if(_.rd(a))_.C(a,"complete"),_.C(a,"success");else{a.g=6;var b;try{b=2<pd(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+_.qd(a)+"]";md(a)}}finally{nd(a)}}};nd=function(a,b){if(a.a){jd(a);var c=a.a,d=a.A[0]?_.la:null;a.a=null;a.A=null;b||_.C(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
jd=function(a){a.a&&a.V&&(a.a.ontimeout=null);_.ia(a.v)&&(_.$c(a.v),a.v=null)};_.rd=function(a){var b=_.qd(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.M).match(_.ad)[1]||null,!a&&_.k.self&&_.k.self.location&&(a=_.k.self.location.protocol,a=a.substr(0,a.length-1)),b=!dd.test(a?a.toLowerCase():"");c=b}return c};pd=function(a){return a.a?a.a.readyState:0};_.qd=function(a){try{return 2<pd(a)?a.a.status:-1}catch(b){return-1}}; Ib(function(a){_.cd.prototype.O=a(_.cd.prototype.O)});
var yd,Gd,zd,Bd,Ad,Ed,Cd,Hd;_.D=function(a,b){this.b=this.j=this.h="";this.g=null;this.l=this.a="";this.F=!1;var c;a instanceof _.D?(this.F=_.m(b)?b:a.F,_.sd(this,a.h),this.j=a.j,this.b=a.b,_.td(this,a.g),this.a=a.a,_.ud(this,a.c.clone()),_.vd(this,a.l)):a&&(c=String(a).match(_.ad))?(this.F=!!b,_.sd(this,c[1]||"",!0),this.j=_.wd(c[2]||""),this.b=_.wd(c[3]||"",!0),_.td(this,c[4]),this.a=_.wd(c[5]||"",!0),_.ud(this,c[6]||"",!0),_.vd(this,c[7]||"",!0)):(this.F=!!b,this.c=new _.xd(null,0,this.F))};
_.D.prototype.toString=function(){var a=[],b=this.h;b&&a.push(yd(b,zd,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(yd(b,zd,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.g,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(yd(c,"/"==c.charAt(0)?Ad:Bd,!0));(c=this.c.toString())&&a.push("?",c);(c=this.l)&&a.push("#",yd(c,Cd));return a.join("")};_.D.prototype.clone=function(){return new _.D(this)};
_.sd=function(a,b,c){a.h=c?_.wd(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};_.td=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("p`"+b);a.g=b}else a.g=null};_.ud=function(a,b,c){b instanceof _.xd?(a.c=b,Dd(a.c,a.F)):(c||(b=yd(b,Ed)),a.c=new _.xd(b,0,a.F))};_.vd=function(a,b,c){a.l=c?_.wd(b):b;return a};_.Fd=function(a){return a instanceof _.D?a.clone():new _.D(a,void 0)};
_.wd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};yd=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Gd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Gd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};zd=/[#\/\?@]/g;Bd=/[\#\?:]/g;Ad=/[\#\?]/g;Ed=/[\#\?@]/g;Cd=/#/g;_.xd=function(a,b,c){this.b=this.a=null;this.c=a||null;this.g=!!c};
Hd=function(a){a.a||(a.a=new _.z,a.b=0,a.c&&bd(a.c,function(b,c){var d=(0,window.decodeURIComponent)(b.replace(/\+/g," "));Hd(a);a.c=null;var d=Id(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.b++}))};_.xd.prototype.ta=function(){Hd(this);return this.b};_.xd.prototype.remove=function(a){Hd(this);a=Id(this,a);return _.Ab(this.a,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};_.xd.prototype.clear=function(){this.a=this.c=null;this.b=0};
_.xd.prototype.la=function(){Hd(this);return 0==this.b};var Jd=function(a,b){Hd(a);b=Id(a,b);return _.Ab(a.a,b)};_.xd.prototype.ba=function(){Hd(this);for(var a=this.a.U(),b=this.a.ba(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.xd.prototype.U=function(a){Hd(this);var b=[];if(_.t(a))Jd(this,a)&&(b=_.Ha(b,this.a.get(Id(this,a))));else{a=this.a.U();for(var c=0;c<a.length;c++)b=_.Ha(b,a[c])}return b};
_.xd.prototype.set=function(a,b){Hd(this);this.c=null;a=Id(this,a);Jd(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b++;return this};_.xd.prototype.get=function(a,b){var c=a?this.U(a):[];return 0<c.length?String(c[0]):b};_.Kd=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(Id(a,b),_.Ia(c)),a.b+=c.length)};
_.xd.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.ba(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.U(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.c=a.join("&")};_.xd.prototype.clone=function(){var a=new _.xd;a.c=this.c;this.a&&(a.a=this.a.clone(),a.b=this.b);return a}; var Id=function(a,b){var c=String(b);a.g&&(c=c.toLowerCase());return c},Dd=function(a,b){b&&!a.g&&(Hd(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Kd(this,e,a))},a));a.g=b};
var Ld,Md,Nd,Od,Qd;Ld=_.y("Firefox");Md=$a()||_.y("iPod");Nd=_.y("iPad");Od=_.y("Android")&&!(Za()||_.y("Firefox")||Ya()||_.y("Silk"));_.Pd=Za();Qd=_.y("Safari")&&!(Za()||_.y("Coast")||Ya()||_.y("Edge")||_.y("Silk")||_.y("Android"))&&!($a()||_.y("iPad")||_.y("iPod"));
var Rd;Rd=function(a){return(a=a.exec(_.Va))?a[1]:""};_.Sd=function(){if(Ld)return Rd(/Firefox\/([0-9.]+)/);if(_.cb||db||bb)return mb;if(_.Pd)return Rd(/Chrome\/([0-9.]+)/);if(Qd&&!($a()||_.y("iPad")||_.y("iPod")))return Rd(/Version\/([0-9.]+)/);if(Md||Nd){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Va))return a[1]+"."+a[2]}else if(Od)return(a=Rd(/Android\s+([0-9.]+)/))?a:Rd(/Version\/([0-9.]+)/);return""}();
var Td=function(a){this.b=a;this.c="empty";this.a=null};Td.prototype.setVersion=function(a){this.c=a;return this};Td.prototype.lb=function(a){this.a=a;return this};var Ud=function(){};var Vd=function(){};_.q(Vd,Ud);Vd.prototype.ta=function(){var a=0;wb(this.Aa(!0),function(){a++});return a};Vd.prototype.clear=function(){var a=xb(this.Aa(!0)),b=this;(0,_.w)(a,function(a){b.remove(a)})};var Wd=function(a){this.a=a};_.q(Wd,Vd);_.g=Wd.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.t(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ta=function(){return this.a.length};_.g.Aa=function(a){var b=0,c=this.a,d=new ub;d.next=function(){if(b>=c.length)throw tb;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.t(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var Xd=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.q(Xd,Wd);var Zd=function(a,b){this.c=a;this.a=[];this.b=null;b&&(this.b=new Xd);if(null!=this.b&&this.b.isAvailable()){var c=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate");if(null!=c)try{this.a=Ja(c)||[]}catch(d){}}c=!1;_.v(this.a)||(this.a=[],c=!0);for(;this.a.length>this.c;)this.a.shift(),c=!0;c&&Yd(this)},Yd=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Ma(a.a))}catch(b){}};
_.$d=function(a){_.x.call(this);this.a=a;this.c=!1};_.q(_.$d,_.x);_.$d.prototype.setEnabled=function(a){this.c=a};var E=function(a){_.$d.call(this,a);this.D=100;this.j={};this.aa=null;this.l="";this.v=!0;this.g=10;this.b=null;this.w=!1};_.q(E,_.$d);E.prototype.fd=function(a){this.v=a;return this};E.prototype.setUseLocalStorage=E.prototype.fd;E.prototype.ff=function(a){this.g=Math.min(a,100);return this};E.prototype.setMaxErrorsPerHour=E.prototype.ff;E.prototype.ed=function(a){this.D=a;return this};E.prototype.setGlobalSampling=E.prototype.ed;E.prototype.wc=function(a,b){this.j[a]=b;return this};
E.prototype.addPerErrorMessageSampling=E.prototype.wc;E.prototype.cd=function(a){this.aa=a;return this};E.prototype.setCallback=E.prototype.cd;E.prototype.dd=function(a){this.l=a;return this};E.prototype.setClientId=E.prototype.dd;E.prototype.enable=function(){if(this.c)return!1;this.h=window.onerror;window.onerror=this.B.bind(this);this.setEnabled(!0);return!0};E.prototype.enable=E.prototype.enable;
E.prototype.Zc=function(a,b,c,d,e){var f=_.Fd(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ha(this.aa)||this.aa(f.a,a,b,c,d,e)){h=Object.keys(this.j);for(var n=100,p=0;p<h.length;++p){var u=h[p];(new RegExp(u)).test(a)&&(n=this.j[u])}if(h=(100*Math.random()).toFixed(6)>=this.D*n/100?!1:!0){0<=this.g&&null===this.b&&(this.b=new Zd(this.g,this.v));if(null===this.b)h=0;else{a:{h=this.b;n=(0,_.l)();if(h.a.length==h.c)if(h.a[0]<n-36E5)h.a.shift();else{h=!1;break a}h.a.push(n);
Yd(h);h=!0}h=!h}h=!h}}h&&(h=ae(this,f,a,b,c,d),h.product=this.a.b,h.version=this.a.c,be(this,"https://clients2.google.com/webmon",ce(h),de(a,null!=e?_.sa(e.stack):"")),this.w&&(b=ae(this,f,a,b,c,d),b.prod=this.a.b,b.ver=this.a.c,be(this,"https://clients2.google.com/cr/staging_report",ce(b),de(a,null!=e?_.sa(e.stack):"")),e={product:this.a.b,url:f.a,js_errors_count:"1"},f=_.sa(this.a.a),_.oa(f)||(e.version=f),be(this,"https://clients2.google.com/cr/staging_perf",ce(e))))};E.prototype.reportError=E.prototype.Zc;
E.prototype.B=function(a,b,c,d,e){this.Zc(a,b,c,d,e);null!=this.h&&_.ha(this.h)&&this.h(a,b,c,d,e)};
var ae=function(a,b,c,d,e,f){b=b.a;var h;h="Other";bb?h="Opera":_.cb?h="Internet Explorer":Ld?h="Firefox":_.Pd?h="Chrome":Qd&&(h="Safari");var n=_.y("CrOS")?"Chrome OS":_.y("Linux")?"Linux":_.ab()?"Windows":_.y("Android")?"Android":$a()?"iPhone":_.y("iPad")?"iPad":_.y("iPod")?"iPod":_.y("Macintosh")?"Mac":"Unknown",p=_.Va,u="";_.ab()?(u=/Windows (?:NT|Phone) ([0-9.]+)/,u=(p=u.exec(p))?p[1]:"0.0"):$a()||_.y("iPad")||_.y("iPod")?(u=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,u=(p=u.exec(p))&&p[1].replace(/_/g,
".")):_.y("Macintosh")?(u=/Mac OS X ([0-9_.]+)/,u=(p=u.exec(p))?p[1].replace(/_/g,"."):"10"):_.y("Android")?(u=/Android\s+([^\);]+)(\)|;)/,u=(p=u.exec(p))&&p[1]):_.y("CrOS")&&(u=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,u=(p=u.exec(p))&&p[1]);c={url:b,type:"JavascriptError",error_message:c,browser:h,browser_version:_.Sd,os:n,os_version:u||""};null!=a.a.a&&(c.channel=a.a.a);_.oa(a.l)||(c.guid=a.l);null!=d&&(c.src=d);null!=e&&(c.line=e);null!=f&&(c.column=f);return c},de=function(a,b){if(_.oa(a))return b;
var c=b.split("\n");-1<c[0].indexOf(a)&&(c.splice(0,1),b=c.join("\n"));return b},ce=function(a){var b="",c;for(c in a)b+=_.oa(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},be=function(a,b,c,d){d=d||"";var e=_.oa(d)?{}:{"Content-Type":"text/plain"};_.gd(b+c,a.A.bind(a,b),"POST",d,e,6E4,!0)};E.prototype.A=function(a,b){_.rd(b.target)};
var ee=function(a){_.x.call(this);this.ga=new Td(a);this.a={}};_.q(ee,_.x);_.fa("webmonitoring.Monitoring",ee);ee.prototype.setVersion=function(a){this.ga.setVersion(a);return this};ee.prototype.setVersion=ee.prototype.setVersion;ee.prototype.lb=function(a){this.ga.lb(a);return this};ee.prototype.setChannel=ee.prototype.lb;ee.prototype.tb=function(){null!=this.a[2]||(this.a[2]=new E(this.ga));return this.a[2]};ee.prototype.createJsErrorsReporter=ee.prototype.tb;
var fe=function(a){ee.call(this,a)};_.q(fe,ee);fe.prototype.setVersion=function(a){return fe.H.setVersion.call(this,a)};fe.prototype.lb=function(a){return fe.H.lb.call(this,a)};fe.prototype.tb=function(){var a=fe.H.tb.call(this);a.w=!0;return a};_.ge=function(){ee.call(this,"ultraviolet");this.setVersion(window.chrome.runtime.id)};_.q(_.ge,fe);_.ka(_.ge);_.he=function(){_.ge.Ja().tb().fd(!1).ed(100).wc("Script error.",0).enable()};_.ge.Ja();
}catch(e){_._DumpException(e)}
try{
_.Nh="https://support.google.com/chrome/answer/185277?hl="+window.chrome.i18n.getMessage("@@ui_locale");window.chrome.i18n.getMessage("@@ui_locale");_.Oh="https://support.google.com/hangouts/?p=chrome_desktop_app_outdated&hl="+window.chrome.i18n.getMessage("@@ui_locale");

}catch(e){_._DumpException(e)}
try{
_.fa("_DumpException",function(a){window.console.error(a.stack)});_.he();window.open("","centralRoster")._OnUiFrameReady(window);
}catch(e){_._DumpException(e)}
}).call(this,this.default_uiframehook);
// Google Inc.
