# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1446771554);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1446771737);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1448217768);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1446771434);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1446771314);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1446771857);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151102093730");
user_pref("browser.slowStartup.averageTime", 3403);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20151102093730");
user_pref("browser.startup.homepage_override.mstone", "42.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1448217711570");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1448217713949");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1448304113949");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1446647620107");
user_pref("datareporting.policy.firstRunTime", "1446647557173");
user_pref("datareporting.sessions.current.activeTicks", 15);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2860);
user_pref("datareporting.sessions.current.main", 357);
user_pref("datareporting.sessions.current.sessionRestored", 2923);
user_pref("datareporting.sessions.current.startTime", "1448217646625");
user_pref("datareporting.sessions.current.totalTime", 129);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.prunedIndex", 2);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:42.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1446771554);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "42.0");
user_pref("extensions.lastPlatformVersion", "42.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"41.0.2\",\"st\":1446745294000,\"mt\":1446458683000}}}");
user_pref("gecko.buildID", "20151102093730");
user_pref("gecko.mstone", "42.0");
user_pref("idle.lastDailyNotification", 1446647895);
user_pref("media.gmp-manager.buildID", "20151102093730");
user_pref("media.gmp-manager.lastCheck", 1448217710);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1446647895);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1446647895);
user_pref("toolkit.startup.last_success", 1448217646);
user_pref("toolkit.telemetry.cachedClientID", "08779aca-ec1d-4a1d-b225-866f754d17d8");
user_pref("toolkit.telemetry.previousBuildID", "20151102093730");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
